### ISSUE TITLE
Diff anomalies in misc/`bibxml2` mappings

### ISSUE THREAD

**Issue by strogonoff** [ietf-tools/bibxml-service#222]
Need help reviewing the responses for xml2rfc `bibxml2` paths.

1. Download the report: [bibxml2-report.zip](https://github.com/ietf-ribose/bibxml-service/files/8984543/bibxml2-report.zip). [0]
2. Open the HTML file (it’s a self-contained HTML file with bits of inline JS and CSS)
3. Click “Hide paths w/o diff”
4. Enter “manual” into the search field

Now, only paths that were manually mapped and which return different XML from before will be shown. Anomalies I encountered with these:

- Judging by XML contents (e.g., publication dates), some of them return different documents.

  Examples: `reference.FIPS.1-1.1980.xml` (different year), `reference.IEEE.802-11.1999.xml` (also different year, however titles seem to mostly match?)

- Some return significantly less data.

  Example: `reference.W3C.xpath.xml` (no author info, etc.)

From a cursory check, diffs for _automatically_ resolved paths did not show such anomalies (but not diffs all were inspected).

[0] Note: this report contains responses from BibXML service and xml2rfc tools for a random subset of paths the tool (gathered until xml2rfc tools stopped responding), there may be more anomalies if we were to test the entire list of paths.

**Comment by ronaldtse** [comment]
@strogonoff I don't seem to see any data in the HTML -- the HTML file only provides a pretty much empty log.

* As with why the reference docs are different -- the original data in bibxml2 contain mistakes.

* In the case of W3C references, the references in bibxml2 are "undated references", i.e. there exists multiple versions of XLink, but the W3C reference of xlink is to the "current version" of it. We cannot return more information unless it is a "dated reference", which does exist in the dataset.

**Comment by strogonoff** [comment]
@ronaldtse Did you see “Processed paths”? It’s a summary of an expandable details tag. I agree it’s not obvious…

**Comment by strogonoff** [comment]
Here is an example: https://dev.bibxml.org/management/xml2rfc-compat/bibxml2/reference.FIPS.1-1.1980.xml/ (click “Test resolution”)

Here’s diff in the above HTML report:
<img width="1271" alt="Screenshot 2022-06-28 at 1 15 30 PM" src="https://user-images.githubusercontent.com/292959/176106601-87a3fc3d-362f-49fc-adaa-b70cc4e810d2.png">

There’s mismatching year and title. The original (http://xml2rfc.tools.ietf.org/public/rfc/bibxml2/reference.FIPS.1-1.1980.xml) specifies 1980, it’s in the URL as well.

**Comment by ronaldtse** [comment]
## Problematic: W3C references

The W3C references see larger changes because they are mapping to the undated reference instead of the dated reference.

* [ ] Mapping diffs: re-map W3C references from `bibxml2` to dated references

<img width="846" alt="Screenshot 2022-07-15 at 9 40 50 AM" src="https://user-images.githubusercontent.com/11865/179124015-dfd7dcf6-4bed-41ce-95bd-99bb213ff09a.png">

1. In order to provide actual authorship data, we must map to the dated references (not the undated references). We need to update the mappings.
2. Notice that the anchor is set to `W3C xpath` instead of `W3C.xpath`. This needs to be fixed in the BibXML Service.

## Problematic: Reference files that start with `_reference.W3C.{name}`

These files seem to directly fall back to the backup files without any XML processing. We want the `_reference.W3C.{name}` paths to resolve to `reference.W3C.{name}`.

* [ ] Mapping diffs: `_reference.W3C.{name}` should be processed by the BibXML service as `reference.W3C.{name}` 

<img width="836" alt="Screenshot 2022-07-15 at 9 38 52 AM" src="https://user-images.githubusercontent.com/11865/179123809-41296d49-d549-48b3-9cf5-4026ab1c4659.png">

The other `_reference.{publisher name}.{name}` patterns to be processed by the BibXML Service.

<img width="838" alt="Screenshot 2022-07-15 at 9 39 47 AM" src="https://user-images.githubusercontent.com/11865/179123908-9b3cc09f-1488-442e-a2a8-dfe58d643142.png">

## Problematic: NIST references

The BibXML Service needs to be fixed here.

* [ ] Mapping diffs: NIST references are not using the new data

For example, NIST SP 500-116 is available at:
https://github.com/relaton/relaton-data-nist/blob/main/data/NIST_SP_500-166.yaml

The BibXML content is not reflecting the correct data right now.
<img width="843" alt="Screenshot 2022-07-15 at 9 48 09 AM" src="https://user-images.githubusercontent.com/11865/179124723-9a9a2253-8956-4413-97cf-a22e3184cfe2.png">

## Problematic: diffs should be XML normalized

We're now seeing a lot of diffs that represent identical XML data.

e.g.
<img width="843" alt="Screenshot 2022-07-15 at 9 49 37 AM" src="https://user-images.githubusercontent.com/11865/179124826-d1588870-a5d7-484a-8e8b-e30462555f2f.png">

There are a few problems:
* [ ] Mapping diffs: XML should be normalized before comparison: it will get rid of the attribute ordering
* [ ] Mapping diffs: BibXML service needs to return the XML headings of: `<?xml version="1.0"?>` and `<!DOCTYPE reference SYSTEM "rfc2629.dtd">`
* [ ] Mapping diffs: BibXML service needs to remove `<author><organization abbrev="IETF">Internet Engineering Task Force</organization></author>` because the bibliographic item does not technically originate from IETF.

## OASIS references

OASIS references use a direct fallback. We actually now have the full dataset of OASIS references available in Relaton. It is not part of the RFP but perhaps would be useful for the future to provide authoritative data.

<img width="847" alt="Screenshot 2022-07-15 at 9 43 40 AM" src="https://user-images.githubusercontent.com/11865/179124267-6877c2f6-c54b-44a2-9982-cd910613bdfa.png">

## IEEE references

The IEEE references are now showing a lot more information and correct data. Which is excellent.
<img width="846" alt="Screenshot 2022-07-15 at 9 42 43 AM" src="https://user-images.githubusercontent.com/11865/179124174-740c36c5-b962-482c-9d66-f077f51a6ec8.png">

**Comment by ronaldtse** [comment]
@rjsparks I believe this ticket is completed.

@strogonoff can you confirm?

**Comment by strogonoff** [comment]
@ronaldtse Thank you for looking into the discrepancies! I couldn’t in some cases tell what’s OK and what’s not. I think we can consider it resolved…

And after big changes to path resolution and bibxml serialization we can run the test_paths.py script again if necessary.
