### ISSUE TITLE
Some entries doesn't have `.xml` API URLs

### ISSUE THREAD

**Issue by kesara** [ietf-tools/bibxml-service#281]
### Describe the issue

Example:
* https://bib.ietf.org/get-bibliographic-item/?query=RFC+9000
* https://bib.ietf.org/get-bibliographic-item/?query=I-D.li-lsr-ospfv3-srv6-extensions

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by strogonoff** [comment]
These are cases with source data issues (that we discussed). The final deserialization step raises validation errors, because of which we don’t end up with a fully initialized instance.

Sentry should have events “Failed to reverse xml2rfc URLs for item …” reported.

**Comment by ronaldtse** [comment]
This was fixed by @strogonoff in #282. The following screenshots confirm the fix. Thanks @strogonoff !

https://bib.ietf.org/get-bibliographic-item/?query=RFC+9000
<img width="711" alt="Screen Shot 2022-08-31 at 4 13 14 PM" src="https://user-images.githubusercontent.com/11865/187628210-2faad3b0-b30d-49ad-9a40-891a44139586.png">

https://bib.ietf.org/public/rfc/bibxml/reference.RFC.9000.xml
<img width="825" alt="Screen Shot 2022-08-31 at 4 12 43 PM" src="https://user-images.githubusercontent.com/11865/187628056-c57de034-2322-4b8d-8755-771e30bbe812.png">

https://bib.ietf.org/get-bibliographic-item/?query=I-D.li-lsr-ospfv3-srv6-extensions
<img width="895" alt="Screen Shot 2022-08-31 at 4 13 49 PM" src="https://user-images.githubusercontent.com/11865/187628406-619acbb9-353f-4c3c-aeb4-b7bc1134ff83.png">

https://bib.ietf.org/public/rfc/bibxml3/reference.I-D.draft-li-lsr-ospfv3-srv6-extensions-00.xml
<img width="964" alt="Screen Shot 2022-08-31 at 4 11 55 PM" src="https://user-images.githubusercontent.com/11865/187627840-c06ad4cb-6a95-476f-aeae-d7d28a199ffe.png">
