### ISSUE TITLE
Support Editorial Stream

### ISSUE THREAD

**Issue by ronaldtse** [ietf-tools/bibxml-service#301]
### Description

As described in https://github.com/ietf-tools/xml2rfc/issues/896

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
@ronaldtse - this should get attention in the next couple of months - support for the editorial stream is already in xml2rfc and will be in the datatracker within the next few weeks.

**Comment by ronaldtse** [comment]
Thank you @rjsparks for the notice. We will implement the necessary changes.

**Comment by rjsparks** [comment]
fwiw, This did make it into last week's datatracker deployment.

**Comment by strogonoff** [comment]
@ronaldtse  Are streams part of our bibliographic data model? I couldn’t find them in the RNC spec.

(If this belongs to bibliographic data then we should update the models, and if this belongs only to actual document contents then perhaps it’s not in scope of the service? It could be both, like in case of the abstract.)

**Comment by opoudjis** [comment]
Streams in the bibliographic model have been modelled as they have been in RFC XML, as series: https://datatracker.ietf.org/doc/html/rfc7991#section-2.47.5

````
<bibitem>
....
                <series type='stream'>
                   <title>editorial</title>
                   </series>
....
</bibitem>
````

That means that we have not modelled streams as a controlled vocabulary, since series are titled with free text. 

I will not accept an extension point for streams: streams are part of referencing documents, and documents must not be referenced with flavour-specific information, that is constrained to document-internal metadata (the extension point.)

**Comment by stefanomunarini** [comment]
Thanks @opoudjis and @rjsparks for the clarification. I will close this issue for now. Feel free to reopen it if you think if becomes of relevance at a certain point in the future.
