### ISSUE TITLE
Review target for data sets

### ISSUE THREAD

**Issue by kesara** [ietf-tools/bibxml-service#341]
I think we need to review what should be the target for each data set and whether the target should be removed from unstable datasets.

>...
> Do we have a path where we can restore target only for one of the datasets at this >time? (bibxml-rfc)
>We have things to work out with the other datasets for what target should contain - >for RFCs the answer is reasonably stable.

_Originally posted by @rjsparks in https://github.com/ietf-tools/bibxml-service/issues/340#issuecomment-1429870921_

**Comment by stefanomunarini** [comment]
@rjsparks does this mean that the `target` attribute should only be outputted for relaton-data-rfcs data? All other datasets (IDs, IEEE, W3C, etc.) won't have `target` attribute at all? Please confirm before I move on with the fix.

**Comment by rjsparks** [comment]
At the time I asked the question, yes, that's what it meant. But ignore it - we have some workarounds that will allow RFCs to continue to be produced as we normalize this. Having target come back should be fine for all datasets. If that turns out to not be so, we'll raise a flag.

Note that sometime later in the week, I will recompute the source data for bibxml-ids changing the targets there and we will need to make sure that propagates correctly.

**Comment by stefanomunarini** [comment]
Acknowledged! The `target` attribute is now restored for all datasets. I am closing this issue now but feel free to reopen it, or create a new one, if things need to be changed.
