### ISSUE TITLE
BibXML fails to output XML for set of drafts

### ISSUE THREAD

**Issue by kesara** [ietf-tools/bibxml-service#398]
### Describe the issue

Draft: https://bib.ietf.org/indexed-sources/relaton-data-ids/draft-irtf-cfrg-kangarootwelve/

From revisions 05-10 gives an error, while [04](https://bib.ietf.org/public/rfc/bibxml3/reference.I-D.draft-irtf-cfrg-kangarootwelve-04.xml) and older and [12 (latest)](https://bib.ietf.org/public/rfc/bibxml3/reference.I-D.draft-irtf-cfrg-kangarootwelve-12.xml) works fine.
Example:
* https://bib.ietf.org/public/rfc/bibxml3/reference.I-D.draft-irtf-cfrg-kangarootwelve-05.xml
* https://bib.ietf.org/public/rfc/bibxml3/reference.I-D.draft-irtf-cfrg-kangarootwelve-10.xml

```
{
  "error": {
    "message": "Error resolving bibliographic item. Tried methods: auto (InternetDraftsAdapter: using query (@.type == \"Internet-Draft\") && (@.id == \"draft-irtf-cfrg-kangarootwelve-10\")): , fallback (): not indexed"
  }
}
```

BibXML data for [05](https://bib.ietf.org/get-bibliographic-item/?query=draft-irtf-cfrg-kangarootwelve-05) to [06](https://bib.ietf.org/get-bibliographic-item/?query=draft-irtf-cfrg-kangarootwelve-06) exists but there's an issue with one of the author names. The author name issue has to be fixed on Datatracker.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment]
This is due to the same root issue that https://github.com/ietf-tools/datatracker/issues/4933 and the issues related to it discuss (I'm pointing to that closed one because it explains the problem most quickly). The datatracker does not have the metadata for those versions of the documents.

Unlike displaying draft content, working around not having DocHistory for bibxml is far more dangerous - the datatracker doesn't know who the authors were for each version. We could teach it (there are thousands of older draft versions in this shape) manually, but we'd need a way to say we didn't know about _other_ metadata that would go into the dochistory (like if there was a shepherd set).

**Comment by rjsparks** [comment]
Ah - that's not the problem for the kangarootwelve document. Bibxml needs to be regenerated for that document.

**Comment by rjsparks** [comment]
The datatracker generated source of truth exists for all versions of this file. Is there anything showing where processing what the datatracker is providing is breaking?

**Comment by kesara** [comment]
#400 fixed this as well.
